// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqbttunwifishjxsreur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxYnR0dW53aWZpc2hqeHNyZXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTgxNjEsImV4cCI6MjA3MDAzNDE2MX0.MedXgZ8-4GZkv8p9o2E90QqiOF3S8ACLfPNnupHnvNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});